manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: ftc-dodubassman
      url-base: https://github.com/dodubassman
  projects:
    - name: zmk
      remote: ftc-dodubassman
      revision: mouse-ftc
      import: app/west.yml
  self:
    path: config
